#!/bin/sh

if [ ! -d /mnt/sdcard/Saves/userdata-flip ]; then
     log_message "Saves/userdata-flip does not exist. Populating surrogate /userdata directory"
    mkdir /mnt/sdcard/Saves/userdata-flip
    cp -R /userdata/* /mnt/sdcard/Saves/userdata-flip
    mkdir -p /mnt/sdcard/Saves/userdata-flip/bin
    mkdir -p /mnt/sdcard/Saves/userdata-flip/bluetooth
    mkdir -p /mnt/sdcard/Saves/userdata-flip/cfg
    mkdir -p /mnt/sdcard/Saves/userdata-flip/localtime
    mkdir -p /mnt/sdcard/Saves/userdata-flip/timezone
    mkdir -p /mnt/sdcard/Saves/userdata-flip/lib
    mkdir -p /mnt/sdcard/Saves/userdata-flip/lib/bluetooth
fi


mount --bind /mnt/sdcard/Saves/userdata-flip/ /userdata
mkdir -p /run/bluetooth_fix
mount --bind /run/bluetooth_fix /userdata/bluetooth

/mnt/sdcard/spruce/flip/recombine_large_files.sh &>> /mnt/sdcard/Saves/spruce/spruce.log
/mnt/sdcard/spruce/flip/setup_32bit_chroot.sh &>> /mnt/sdcard/Saves/spruce/spruce.log
/mnt/sdcard/spruce/flip/mount_muOS.sh &>> /mnt/sdcard/Saves/spruce/spruce.log
/mnt/sdcard/spruce/flip/setup_32bit_libs.sh &>> /mnt/sdcard/Saves/spruce/spruce.log
/mnt/sdcard/spruce/flip/bind_glibc.sh &>> /mnt/sdcard/Saves/spruce/spruce.log


# Mask Roms/PORTS with non-A30 version
mkdir -p "/mnt/SDCARD/Roms/PORTS64"
mount --bind "/mnt/SDCARD/Roms/PORTS64" "/mnt/SDCARD/Roms/PORTS" &

# PortMaster ports location
mkdir -p /mnt/sdcard/Roms/PORTS64/ports/ 
mount --bind /mnt/sdcard/Roms/PORTS64/ /mnt/sdcard/Roms/PORTS64/ports/
	
# Treat /spruce/flip/ as the 'root' for any application that needs it.
# (i.e. PortMaster looks here for config information which is device specific)
mount --bind /mnt/sdcard/spruce/flip/ /root 

# Bind the correct version of retroarch so it can be accessed by PM
mount --bind /mnt/sdcard/RetroArch/retroarch-flip /mnt/sdcard/RetroArch/retroarch


export PYSDL2_DLL_PATH="/mnt/SDCARD/App/PyUI/dll"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/miyoo/lib"

touch /tmp/fbdisplay_exit
cat /dev/zero > /dev/fb0


/usr/miyoo/bin/miyoo_inputd &
/usr/miyoo/bin/hardwareservice &

/mnt/SDCARD/spruce/flip/bin/python3 /mnt/sdcard/App/PyUI/main-ui/MainUI.py


